"""Initial database setup

Revision ID: 22d49272385b
Revises: 
Create Date: 2024-03-19 17:07:25.509975

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22d49272385b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job',
    sa.Column('job_no', sa.String(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('locked', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('job_no')
    )
    op.create_table('users',
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('alias', sa.String(length=80), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('dept', sa.String(length=50), nullable=True),
    sa.Column('reporting_officer_name', sa.String(length=80), nullable=True),
    sa.Column('is_global_admin', sa.Boolean(), nullable=False),
    sa.Column('is_dept_admin', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['reporting_officer_name'], ['users.name'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('name'),
    sa.UniqueConstraint('number')
    )
    op.create_table('job_system',
    sa.Column('job_no', sa.String(), nullable=False),
    sa.Column('root_name', sa.String(length=80), nullable=True),
    sa.ForeignKeyConstraint(['job_no'], ['job.job_no'], ),
    sa.PrimaryKeyConstraint('job_no')
    )
    op.create_table('job_unknown',
    sa.Column('job_no', sa.String(), nullable=False),
    sa.Column('from_no', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['job_no'], ['job.job_no'], ),
    sa.PrimaryKeyConstraint('job_no')
    )
    op.create_table('job_user',
    sa.Column('job_no', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.Column('is_cancelled', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['job_no'], ['job.job_no'], ),
    sa.PrimaryKeyConstraint('job_no')
    )
    op.create_table('message',
    sa.Column('sid', sa.String(length=80), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('body', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('seq_no', sa.Integer(), nullable=False),
    sa.Column('job_no', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['job_no'], ['job.job_no'], ),
    sa.PrimaryKeyConstraint('sid')
    )
    op.create_table('metrics',
    sa.Column('_type', sa.String(length=30), nullable=False),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('last_update', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_successful_update', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_job_no', sa.String(), nullable=True),
    sa.Column('last_successful_job_no', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['last_job_no'], ['job.job_no'], ),
    sa.ForeignKeyConstraint(['last_successful_job_no'], ['job.job_no'], ),
    sa.PrimaryKeyConstraint('_type')
    )
    op.create_table('job_acq_token',
    sa.Column('job_no', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['job_no'], ['job_system.job_no'], ),
    sa.PrimaryKeyConstraint('job_no')
    )
    op.create_table('job_am_report',
    sa.Column('job_no', sa.String(), nullable=False),
    sa.Column('forwards_status', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['job_no'], ['job_system.job_no'], ),
    sa.PrimaryKeyConstraint('job_no')
    )
    op.create_table('job_es',
    sa.Column('job_no', sa.String(), nullable=False),
    sa.Column('category', sa.String(length=20), nullable=True),
    sa.Column('helpful', sa.Boolean(), nullable=True),
    sa.Column('answered', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['job_no'], ['job_user.job_no'], ),
    sa.PrimaryKeyConstraint('job_no')
    )
    op.create_table('job_leave',
    sa.Column('job_no', sa.String(), nullable=False),
    sa.Column('forwards_status', sa.Integer(), nullable=True),
    sa.Column('local_db_updated', sa.Boolean(), nullable=False),
    sa.Column('leave_type', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['job_no'], ['job_user.job_no'], ),
    sa.PrimaryKeyConstraint('job_no')
    )
    op.create_table('job_sync_records',
    sa.Column('job_no', sa.String(), nullable=False),
    sa.Column('forwards_status', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['job_no'], ['job_system.job_no'], ),
    sa.PrimaryKeyConstraint('job_no')
    )
    op.create_table('job_sync_users',
    sa.Column('job_no', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['job_no'], ['job_system.job_no'], ),
    sa.PrimaryKeyConstraint('job_no')
    )
    op.create_table('message_received',
    sa.Column('sid', sa.String(length=80), nullable=False),
    sa.Column('reply_sid', sa.String(length=80), nullable=True),
    sa.ForeignKeyConstraint(['sid'], ['message.sid'], ),
    sa.PrimaryKeyConstraint('sid')
    )
    op.create_table('message_sent',
    sa.Column('sid', sa.String(length=80), nullable=False),
    sa.Column('is_expecting_reply', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['sid'], ['message.sid'], ),
    sa.PrimaryKeyConstraint('sid')
    )
    op.create_table('job_leave_cancel',
    sa.Column('job_no', sa.String(), nullable=False),
    sa.Column('initial_job_no', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['initial_job_no'], ['job_leave.job_no'], ),
    sa.ForeignKeyConstraint(['job_no'], ['job_leave.job_no'], ),
    sa.PrimaryKeyConstraint('job_no'),
    sa.UniqueConstraint('initial_job_no')
    )
    op.create_table('message_confirm',
    sa.Column('sid', sa.String(length=80), nullable=False),
    sa.Column('ref_msg_sid', sa.String(length=80), nullable=False),
    sa.Column('_decision', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['sid'], ['message_received.sid'], ),
    sa.PrimaryKeyConstraint('sid')
    )
    op.create_table('message_forward',
    sa.Column('sid', sa.String(length=80), nullable=False),
    sa.Column('to_name', sa.String(length=80), nullable=False),
    sa.ForeignKeyConstraint(['sid'], ['message_sent.sid'], ),
    sa.PrimaryKeyConstraint('sid')
    )
    op.create_table('leave_records',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('job_no', sa.String(), nullable=False),
    sa.Column('cancelled_job_no', sa.String(), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('sync_status', sa.Integer(), nullable=True),
    sa.Column('is_cancelled', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['cancelled_job_no'], ['job_leave_cancel.job_no'], ),
    sa.ForeignKeyConstraint(['job_no'], ['job_leave.job_no'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('leave_records')
    op.drop_table('message_forward')
    op.drop_table('message_confirm')
    op.drop_table('job_leave_cancel')
    op.drop_table('message_sent')
    op.drop_table('message_received')
    op.drop_table('job_sync_users')
    op.drop_table('job_sync_records')
    op.drop_table('job_leave')
    op.drop_table('job_es')
    op.drop_table('job_am_report')
    op.drop_table('job_acq_token')
    op.drop_table('metrics')
    op.drop_table('message')
    op.drop_table('job_user')
    op.drop_table('job_unknown')
    op.drop_table('job_system')
    op.drop_table('users')
    op.drop_table('job')
    # ### end Alembic commands ###
