"""Added cascade delete to job_no foreign key

Revision ID: 911356fe9f90
Revises: 22d49272385b
Create Date: 2024-04-26 23:44:28.054289

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '911356fe9f90'
down_revision = '22d49272385b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('job_system_job_no_fkey', 'job_system', type_='foreignkey')
    op.create_foreign_key('job_system_job_no_fkey', 'job_system', 'job', ['job_no'], ['job_no'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('job_system_job_no_fkey', 'job_system', type_='foreignkey')
    op.create_foreign_key('job_system_job_no_fkey', 'job_system', 'job', ['job_no'], ['job_no'])
    # ### end Alembic commands ###
