"""Added cascade delete to job no foreign other sys jobs

Revision ID: 9b2a00f6cdcc
Revises: 911356fe9f90
Create Date: 2024-04-27 00:12:13.968122

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b2a00f6cdcc'
down_revision = '911356fe9f90'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('job_acq_token_job_no_fkey', 'job_acq_token', type_='foreignkey')
    op.create_foreign_key('job_acq_token_job_no_fkey', 'job_acq_token', 'job_system', ['job_no'], ['job_no'], ondelete='CASCADE')
    op.drop_constraint('job_sync_records_job_no_fkey', 'job_sync_records', type_='foreignkey')
    op.create_foreign_key('job_sync_records_job_no_fkey', 'job_sync_records', 'job_system', ['job_no'], ['job_no'], ondelete='CASCADE')
    op.drop_constraint('job_sync_users_job_no_fkey', 'job_sync_users', type_='foreignkey')
    op.create_foreign_key('job_sync_users_job_no_fkey', 'job_sync_users', 'job_system', ['job_no'], ['job_no'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('job_sync_users_job_no_fkey', 'job_sync_users', type_='foreignkey')
    op.create_foreign_key('job_sync_users_job_no_fkey', 'job_sync_users', 'job_system', ['job_no'], ['job_no'])
    op.drop_constraint('job_sync_records_job_no_fkey', 'job_sync_records', type_='foreignkey')
    op.create_foreign_key('job_sync_records_job_no_fkey', 'job_sync_records', 'job_system', ['job_no'], ['job_no'])
    op.drop_constraint('job_acq_token_job_no_fkey', 'job_acq_token', type_='foreignkey')
    op.create_foreign_key('job_acq_token_job_no_fkey', 'job_acq_token', 'job_system', ['job_no'], ['job_no'])
    # ### end Alembic commands ###
