name: chatbot
channels:
  - conda-forge
  - defaults
dependencies:
  - pip==21.0.1
  - elasticsearch==8.10.0
  - Flask==2.3.2
  - flask-sqlalchemy=3.0.3
  - msal==1.25.0
  - numpy==1.25.2
  - pandas==2.1.4
  - pdfminer.six==20221105
  - pdfplumber==0.9.0
  - Pillow==10.1.0
  - pytesseract==0.3.13
  - python-dotenv==1.0.0
  - python-dateutil==2.8.2
  - python-docx=1.1.0
  - Requests==2.31.0
  - spacy==3.7.2
  - SQLAlchemy==2.0.23
  - twilio==8.10.1
  - gunicorn==21.2.0
  - psycopg2==2.9.9
  - pytesseract==0.3.13
  - overrides==7.4.0
  - shortuuid==1.0.12
  - alembic==1.13.1
  - pip:
      - docopt==0.6.2
      - pipdeptree==2.13.1
      - pipreqs==0.4.13
      - pymupdf==1.23.6
      - pymupdfb==1.23.6
      - yarg==0.1.9
      - redis==5.0.2